name: Deploy Lanchonete Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./lanchonete

      - name: Build Docker image
        run: docker build -t lanchonete:latest .
        working-directory: ./lanchonete

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Tag Docker image
        run: docker tag lanchonete:latest ${{ secrets.DOCKER_USERNAME }}/lanchonete:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/lanchonete:latest

      - name: Create kube directory
        run: mkdir -p $HOME/.kube

      - name: Decode Kube config
        run: echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region sa-east-1

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name lanchonete-cluster --region sa-east-1

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/lanchonete-deployment lanchonete=${{ secrets.DOCKER_USERNAME }}/lanchonete:latest
